<?php

namespace WebshopBundle\Repository;

/**
 * CartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartsRepository extends \Doctrine\ORM\EntityRepository
{
}
